- name: "hello2"
  path: /test
  controller: helloworld.hello
- name: "foo"
  path: /foo
  controller: helloworld.name(name="Max")
- path: /static/*name
  controller: flamingo.static.file(name,dir?="static")
