- name: "hello.alias"
  path: /alias
  controller: helloworld
- name: "hello.flmaingo"
  path: /flamingo
  controller: hello.name(name="Flamingo")
- path: /static/*name
  controller: flamingo.static.file(name,dir?="static")
